export const CONFIG = {
  PATH: '/tmp/chuchu-save.json',
  GAME_LOOP_MS: 20,
  GAME_LOOP_MIN_MS: 20,    // Fréquence maximale (50 FPS)
  GAME_LOOP_MAX_MS: 50,    // Fréquence minimale (20 FPS)
  ADAPTIVE_FREQUENCY: true, // Active/désactive la fréquence adaptative
  GLOBAL_HEIGHT: 2000,
  GLOBAL_WIDTH: 2000,
  MAX_PLAYERS: 32,
  MIN_PLAYERS: 2,
  QUEUE_TIME: 2,
  RETRY_TIME: 10,
  SERVER_PORT: 8080,
  WSS_PORT: 8081,
  WSS_EXTERNAL_URL: 'ws://localhost:8081',
  AUTO_RECONNECT_DELAY: 100,
  ACTIVITY_TIMEOUT: 1000 * 60 * 5,
  ROWS: 2,
  COLUMNS: 2,
  MAX_PHASES: 10,
  STEP_DURATION: 10000,
  CLASSIC_STEP_GENERATION: 50,
  PLAYER_ABSORB_CAT_RATIO: 0.5,
  PLAYER_ABSORB_MOUSE_POINTS: 1,
  BOTS: 5,
  MAX_MOUSES: 200,
  MAX_CATS: 20,
  BOT_LIMIT_ACTIONS_MS: 1000
} as Record<string, any>;